[package]
name = "vizia_id"
version = "0.1.0"
description = "Core components of vizia"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version = "1.76"

[dependencies]

[lints]
workspace = true
